In [28]:
import pennylane as qml
import numpy as np
from pennylane.templates.layers import RandomLayers

dev = qml.device("default.qubit", wires=2)
n_qlayers = 1
n_qubits = 2
#weights = [[0.1, -2.1, 1.4]]
weights = np.random.uniform(high= 2 * np.pi, size=(n_qlayers, n_qubits))
print("weights\n", weights)

@qml.qnode(dev)
def circuit(inputs, weights):
    qml.templates.AngleEmbedding(inputs, wires=range(n_qubits))
    qml.templates.BasicEntanglerLayers(weights, wires=range(n_qubits))
    return [qml.expval(qml.PauliZ(j)) for j in range(n_qubits)]

inputs = np.random.uniform(high= 2 * np.pi, size=n_qubits)
print("inputs:", inputs)
circuit(inputs, weights)

weights
 [[1.25458737 3.23103027]]
inputs: [3.72225051 0.29185655]


tensor([ 0.26137737, -0.24260625], requires_grad=True)

In [36]:
i

tensor([[[0.3440, 0.0489, 0.2900, 0.0155, 0.8346, 0.6920],
         [0.3543, 0.7785, 0.8638, 0.4819, 0.1136, 0.1644]]])


(tensor([[[0.3440, 0.0489],
          [0.3543, 0.7785]]]),
 tensor([[[0.2900, 0.0155],
          [0.8638, 0.4819]]]),
 tensor([[[0.8346, 0.6920],
          [0.1136, 0.1644]]]))